### ISSUE TITLE
Fetching all containers

### ISSUE THREAD

**Issue by malinois** [abdullahselek/ContactsWrapper#1]
Hello,

The method `fetchContactsWithStore` fetches only the default container. In many cases, when we have an Exchange mail account, we can have many containers, not only the default container.
We can have all of them with `NSArray<CNContainer*> *containers = [[CNContactStore new] containersMatchingPredicate:nil error:nil];`

Can you make the change ?
Thanks!

**Comment by abdullahselek** [comment]
Hi @malinois you can checkout the latest release, thanks for your comments 👍

**Comment by malinois** [comment]
Perfect !
