### ISSUE TITLE
Get contacts number 

### ISSUE THREAD

**Issue by Goule** [abdullahselek/ContactsWrapper#3]
Hello !!

Can I fetch all contact's number with this library ? Or there is Contact model which contains informations about contacts (name, phone..)

Thank you

**Comment by abdullahselek** [comment]
Hi @Goule, yes you can fetch all contact's numbers. Functions used for fetching contacts returns CNContact objects. You can learn more about [CNContact](https://developer.apple.com/reference/contacts/cncontact).

**Comment by Goule** [comment]
Thank you :)
